"""add user api_key

Revision ID: 786888a1190c
Revises: cd28cbb24a49
Create Date: 2021-05-28 18:40:50.302736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786888a1190c'
down_revision = 'cd28cbb24a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('api_key')
    # ### end Alembic commands ###
