"""add User uuid

Revision ID: cd28cbb24a49
Revises: 30b6d27154b5
Create Date: 2021-05-28 14:29:14.903910

"""
from uuid import uuid4

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cd28cbb24a49'
down_revision = '30b6d27154b5'
branch_labels = None
depends_on = None

Base = sa.orm.declarative_base()

class User(Base):
    __tablename__ = 'user'

    id = sa.Column(sa.Integer, primary_key=True)
    uuid = sa.Column(sa.String(64), nullable=False, default=lambda: str(uuid4()))
    username = sa.Column(sa.Text, nullable=False, unique=True)
    password = sa.Column(sa.Text, nullable=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=64), nullable=True))

    session = sa.orm.Session(bind=op.get_bind())
    for user in session.query(User).all():
        user.uuid = str(uuid4())
        session.add(user)
    session.commit()

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('uuid', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
