name: Deploy Blogs

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_ROOT_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            # Ensure MySQL is running.
            systemctl enable mysql
            systemctl start mysql

            # Remove old project if exists.
            cd /opt

            if [ -d "flask_mysql_with_blogs" ]; then

               # Check if inside a virtual environment.

               cd /opt/flask_mysql_with_blogs

               if [ -n "$VIRTUAL_ENV" ]; then
                   echo "Deactivating existing virtual environment: $VIRTUAL_ENV"
                  deactivate
               fi

               rm -rf /opt/flask_mysql_with_blogs

            fi            

            cd /opt

            # Clone repo fresh.
            git clone https://github.com/JoakimKV/flask_mysql_with_blogs.git /opt/flask_mysql_with_blogs

            # Copy secrets from another .env file (.flask_env) into the .env file (.flask_env) 
            # in the project.
            cp /etc/secrets/mysql/keys/.flask_env /opt/flask_mysql_with_blogs/.flask_env

            # Install Python dependencies.

            cd /opt/flask_mysql_with_blogs

            python -m venv venvflask1
            source venvflask1/bin/activate
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

            # Restart Docker app container (Flask only).

            docker compose down
            docker compose --env-file /etc/secrets/mysql/keys/.flask_env up -d --build app

            # Reload Nginx if config changed.

            nginx -t
            systemctl daemon-reload
            systemctl reload nginx
